// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package ma.emsi.tpgrpcbanque.stubs;

public interface DeleteCompteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Success or failure message
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Success or failure message
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
